---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 5
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: database
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true
    # Ref: https://github.com/cloudnative-pg/cloudnative-pg/issues/2501
    podMonitorMetricRelabelings:
      - {sourceLabels: ["cluster"], targetLabel: cnpg_cluster, action: replace}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      data:
        password: '{{ .POSTGRES_SUPER_PASS }}'
        username: "postgres"
  dataFrom:
    - extract:
        key: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.dex136.xyz
    io.cilium/lb-ipam-ips: 192.168.1.241
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    role: primary
