apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: cloudnative-pg
  repo: https://cloudnative-pg.github.io/charts
  version: 0.20.2
  releaseName: database
  valuesFile: helmvalues.yaml
  namespace: database
resources:
- cluster.yaml
