apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.16.1
  releaseName: cert-manager
  valuesFile: helmvalues.yaml
  namespace: network
  includeCRDs: true
resources:
  - clusterissuer.yaml
  - certificates.yaml
