apiVersion: v1
kind: Service
metadata:
  name: statuspage-service
spec:
  selector:
    app: statuspage
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage
spec:
  selector:
    matchLabels:
      app: statuspage
  replicas: 1
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      containers:
      - name: statuspage
        image: ghcr.io/dexter136/statuspage:1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 2m
            memory: 100Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: bottle-tonic-plus
    hajimari.io/group: "monitoring"
    external-dns.alpha.kubernetes.io/hostname: external.dex136.xyz
  name: statuspage
spec:
  ingressClassName: external
  rules:
    - host: statuspage.dex136.xyz
      http:
        paths:
          - backend:
              service:
                name: statuspage-service
                port:
                  number: 6000
            path: /
            pathType: Prefix
  tls:
  - hosts:
      - statuspage.dex136.xyz
