apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: statuspage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: statuspage
    template:
      engineVersion: v2
      data:
        ARGOCD_USER: '{{ .ARGOCD_USER }}'
        ARGOCD_URL: '{{ .ARGOCD_URL }}'
        ARGOCD_PASS: '{{ .ARGOCD_PASS }}'
  dataFrom:
    - extract:
        key: argocd
