---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubernetes
  namespace: {{ .Release.Namespace }}
spec:
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  version: v1.34.1
  concurrency: 1
  exclusive: true
  serviceAccountName: system-upgrade
  secrets:
    - name: system-upgrade
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  upgrade:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    image: ghcr.io/siderolabs/talosctl:v1.10.5
    envs:
      - name: NODE
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --nodes=$(NODE)
      - upgrade-k8s
      - --to=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
