---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media
  resources:
    requests:
      storage: 10Gi
