apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex136-xyz
  namespace: {{ .Release.Namespace }}
spec:
  secretName: dex136-xyz-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dex136.xyz
  dnsNames:
    - dex136.xyz
    - "*.dex136.xyz"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aisling-dev
  namespace: {{ .Release.Namespace }}
spec:
  secretName: aisling-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: aisling.dev
  dnsNames:
    - aisling.dev
    - "*.aisling.dev"
