controllers:
  fstrim:
    type: cronjob
    cronjob:
      schedule: "@weekly"
      parallelism: 5 # Set to my total number of nodes
      successfulJobsHistory: 1
      failedJobsHistory: 1
    containers:
      app:
        image:
          repository: ghcr.io/onedr0p/kubanetics
          tag: 2024.10.3@sha256:9e8e70ac686e9256686e372b27d9a39ab92d6d4c651e67aacedc8ec077a71a66
        env:
          SCRIPT_NAME: fstrim.sh
        resources:
          requests:
            cpu: 25m
          limits:
            memory: 128Mi
        securityContext:
          privileged: true
    pod:
      hostNetwork: true
      hostPID: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: fstrim
persistence:
  procfs:
    type: hostPath
    hostPath: /proc
    hostPathType: Directory
    globalMounts:
      - path: /host/proc
        readOnly: true
  netfs:
    type: hostPath
    hostPath: /sys
    hostPathType: Directory
    globalMounts:
      - path: /host/net
        readOnly: true
