app-template:
  controllers:
    fstrim:
      type: cronjob
      cronjob:
        schedule: "@weekly"
        parallelism: 6
        successfulJobsHistory: 1
        failedJobsHistory: 1
      containers:
        fstrim:
          image:
            repository: ghcr.io/onedr0p/kubanetics
            tag: 2025.3.0@sha256:8305fb9c639a437f1cf6d90f1d0fd8bacad877df7605f6367490618c890225f5
          env:
            SCRIPT_NAME: fstrim.sh
          resources:
            requests:
              cpu: 25m
            limits:
              memory: 128Mi
          securityContext:
            privileged: true
      pod:
        hostNetwork: true
        hostPID: true
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: fstrim
  persistence:
    procfs:
      type: hostPath
      hostPath: /proc
      hostPathType: Directory
      globalMounts:
        - path: /host/proc
          readOnly: true
    netfs:
      type: hostPath
      hostPath: /sys
      hostPathType: Directory
      globalMounts:
        - path: /host/net
          readOnly: true
