---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: minio
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ `{{ .MINIO_ROOT_USER }}` }}"
        MINIO_ROOT_PASSWORD: "{{ `{{ .MINIO_ROOT_PASSWORD }}` }}"
  data:
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: minio.password
        property: password
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: minio.user
        property: password
