apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: kubelet-csr-approver
  repo: https://postfinance.github.io/kubelet-csr-approver
  version: 1.2.4
  releaseName: kubelet-csr-approver
  valuesFile: helmvalues.yaml
  namespace: kube-system
