---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uptime-kuma
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: monitoring
  resources:
    requests:
      storage: 2Gi
