---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpackerr
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpackerr-secret
    template:
      engineVersion: v2
      data:
        UN_SONARR_0_API_KEY: {{"'{{ .SONARR_API_KEY }}'"}}
        UN_RADARR_0_API_KEY: {{"'{{ .RADARR_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
