---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: unpackerr-secret
    template:
      engineVersion: v2
      data:
        UN_SONARR_0_API_KEY: "{{ `{{ .SONARR_API_KEY }}` }}"
        UN_RADARR_0_API_KEY: "{{ `{{ .RADARR_API_KEY }}` }}"
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: sonarr.api
        property: password
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: radarr.api
        property: password
