---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dragonfly-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dragonfly-password
    template:
      engineVersion: v2
      data:
        password: {{"'{{ .DRAGONFLY_PASSWORD }}'"}}
  dataFrom:
    - extract:
        key: dragonfly
