---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prowlarr-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr-exporter
      app.kubernetes.io/instance: prowlarr-exporter
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr-exporter
      app.kubernetes.io/instance: prowlarr-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr-exporter
        app.kubernetes.io/instance: prowlarr-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: prowlarr-exporter
          image: ghcr.io/onedr0p/exportarr:v2.2.0
          imagePullPolicy: IfNotPresent
          args:
            - prowlarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://prowlarr.media.svc.cluster.local:80"
            - name: PROWLARR_BACKFILL
              value: "true"
            - name: ENABLE_ADDITIONAL_METRICS
              value: "true"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-secret
                  key: PROWLARR__AUTH__APIKEY
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__AUTH__APIKEY: {{"'{{ .PROWLARR_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: prowlarr
