apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-token
    template:
      engineVersion: v2
      data:
        api-token: {{"'{{ .CLOUDFLARE_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: cloudflare
