---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_UNIFI_USERNAME: {{"'{{ .UNIFI_USERNAME }}'"}}
        HOMEPAGE_VAR_UNIFI_PASSWORD: {{"'{{ .UNIFI_PASSWORD }}'"}}
        HOMEPAGE_VAR_SONARR_TOKEN: {{"'{{ .SONARR_API_KEY }}'"}}
        HOMEPAGE_VAR_PROWLARR_TOKEN: {{"'{{ .PROWLARR_API_KEY }}'"}}
        HOMEPAGE_VAR_RADARR_TOKEN: {{"'{{ .RADARR_API_KEY }}'"}}
        HOMEPAGE_VAR_AUTOBRR_TOKEN: {{"'{{ .AUTOBRR_API_KEY }}'"}}
        HOMEPAGE_VAR_SEERR_TOKEN: {{"'{{ .SEERR_API_KEY }}'"}}
        HOMEPAGE_VAR_MEALIE_API_KEY: {{"'{{ .MEALIE_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: unifi
    - extract:
        key: radarr
    - extract:
        key: prowlarr
    - extract:
        key: paperless
    - extract:
        key: seerr
    - extract:
        key: tautulli
    - extract:
        key: autobrr
    - extract:
        key: mealie
