---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_UNIFI_USERNAME: {{"'{{ .UNIFI_USERNAME }}'"}}
        HOMEPAGE_VAR_UNIFI_PASSWORD: {{"'{{ .UNIFI_PASSWORD }}'"}}
  dataFrom:
    - extract:
        key: unifi
