---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: &app homepage
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: &app homepage
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: *app
subjects:
  - kind: ServiceAccount
    name: *app
    namespace: default # keep
