---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vl-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: monitoring
  resources:
    requests:
      storage: 20Gi
