apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
data:
    api-token: ENC[AES256_GCM,data:nryqJVyqGzHc7XXYQ69YpQ4br8ceGKFacbFnWMGStjUD7CKAAc1QEBTPU1I5bel6HShIzRkrOaw=,iv:DhXXKY/EXkydlRaCbanIwxiGiGYa4A2F/ZVKXM/+WhM=,tag:J7fYU1tqFLeptfQuQDMP3w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15j6twvva426zpeacwhpmvnfp90v9pctluluxx4v6aldpczulgfqszafkq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc3o2ZkQ5Y2ZpaVFtRjgr
            eXJFaDNYTUF3UEM1MFNmRGd6enNFUVQ2ZVZJCnFSUTl5bHpNbDVHTS9TZmV5dVFG
            Y3lGMERmSG1KZm5BeklXbGd4OTlwQ28KLS0tIHppU05ZRXF4dXpVaTZtemQ1ZWN2
            NVhEUkJkSll6SHcrRS9HYW84Zm53eTAKZGbctR0LWaYRtFPGq4ShA3gjklSdYBrp
            2W2o94uF2EA2exjm/9nxRzQ/EnAvWiSINA7u4QOvDLCMwa1cp5K11Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T20:54:32Z"
    mac: ENC[AES256_GCM,data:0sek3cknl2bF8D+v/jflMZNGqe3UpC0znDRZ+2vqlVkwsFFLVfVULj1aer2SuuaTym2tK1OyTdUH7uPeo735CHxXAfBP3DYnfZ+VnID6yH4mdbxsmCN3EEUrk1a0sC14JlTyjK5IqklncFWemW6ARMbN/DxLz6re0mokMWFRvmI=,iv:Kxg3pPsCIWWwmpD6dnxVPb9gmSyL4UuXmF6R342hZv4=,tag:nz71N2FWUEYHcPu3d11Ilw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
