---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_UNIFI_USERNAME: '{{ .UNIFI_USERNAME }}'
        HOMEPAGE_VAR_UNIFI_PASSWORD: '{{ .UNIFI_PASSWORD }}'
        HOMEPAGE_VAR_SONARR_TOKEN: '{{ .SONARR_API_KEY }}'
        HOMEPAGE_VAR_PROWLARR_TOKEN: '{{ .PROWLARR_API_KEY }}'
        HOMEPAGE_VAR_RADARR_TOKEN: '{{ .RADARR_API_KEY }}'
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: unifi
    - extract:
        key: radarr
    - extract:
        key: prowlarr
