apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
data:
    HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:fN3rWKDnvHn0fbQZ,iv:MimQ1JtkLsRT+mRLZkopsSfbsKLyadsn9owDSsXK74o=,tag:ecWzz8yAQtT/oKN06tWrMw==,type:str]
    HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:7ogYlySM/LaFZtZJywYrHbWVQ1Y=,iv:VtnBSiSnmRHda984h78NkrFeImaLKFc8ydQmAiP8N6I=,tag:djbp1Ptmr54M0S0cS68UVA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15j6twvva426zpeacwhpmvnfp90v9pctluluxx4v6aldpczulgfqszafkq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVnZKbXFBd2ZsUGZjWlNC
            VkI1YUphOUZkaEg5MXdjOXkvTWNDUER6OXdjCnFDQjYwL3haNUwwR1BDdFRsK3lq
            QzFxZG1iKzkvNXA2L252ZlYvUmtiRjQKLS0tIE1UWFNERUh1dmJvcXdyNmduTnJM
            S2lWVU0xUUF0dEVJRHc5RkhZUG9KSncKjHDbDQ7MsriaelZqr9j3PYAlhmvhYFhi
            J83/1vzMpRR6N7PuAfykQuzXY+Q5nRtjmJ42oukB03o8zIlh5kHdag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-27T15:31:48Z"
    mac: ENC[AES256_GCM,data:0O8MHMEbq+HSOwFpheaFX5asFKtcUtWLPzGbcyzl1ZtrI74Lpak2m9a+JIgPqJSkMVPldpX9wri2Kagqh5x+AIv5H/C/wz2Z0S4eR3/lps3deEm4KuVzJ6QLug+1rFbidqH0Lo2iUKOlz5JEqFiVUVf+mnX+M3KhOl+UkWtkm9I=,iv:/aJ5wduYnRnKETyNeQhbF3fCgg5huZuYf8LdD+7hJYA=,tag:fzXfVYRi2ScTY9Z4QmYyOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
