app-template:
  controllers:
    agregarr:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        app:
          image:
            repository: ghcr.io/agregarr/agregarr
            tag: v2.4.1@sha256:6022aef7ad580478bf100ee4b11f19ad689bb780d241e78e33a3ccc6b5feb569
          env:
            PORT: &port 80
            TZ: America/New_York
          probes:
            liveness:
              enabled: true
              spec:
                periodSeconds: 30
                timeoutSeconds: 5
                failureThreshold: 5
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/v1/status
                  port: *port
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 5
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 10
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: ["ALL"]}
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  service:
    app:
      ports:
        http:
          port: *port
  route:
    app:
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Agregarr"
        gethomepage.dev/icon: agregarr.svg
        gethomepage.dev/group: Media
      hostnames:
        - agregarr.aisling.dev
      parentRefs:
        - name: envoy-aisling-dev-internal
          namespace: network
  persistence:
    config:
      existingClaim: agregarr
      globalMounts:
        - path: /app/config
    tmp:
      type: emptyDir
