---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tautulli
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tautulli-secret
    template:
      engineVersion: v2
      data:
        SONARR__AUTH__APIKEY: {{"'{{ .TAUTULLI_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: tautulli
