longhorn:
  longhornUI:
    replicas: 1
  persistence:
    defaultClassReplicaCount: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.dex136.xyz
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
