---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-credentials
    template:
      engineVersion: v2
      data:
        credentials.json: {{"'{{ .CLOUDFLARED_CREDENTIALS }}'"}}
  dataFrom:
    - extract:
        key: cloudflare
