---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - dnsName: external.aisling.dev
      recordType: CNAME
      targets: ["homelab-tunnel.aisling.dev"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    ingress:
      - hostname: 'aisling.dev'
        service: https://envoy-aisling-dev-external.network
        originRequest:
          originServerName: external.aisling.dev
      - hostname: '*.aisling.dev'
        service: https://envoy-aisling-dev-external.network
        originRequest:
          originServerName: external.aisling.dev
      - service: http_status:404
