---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-data
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "longhorn"
  resources:
    requests:
      storage: "1Gi"
