---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mc-mc
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mc-mc
    template:
      engineVersion: v2
      data:
        RCON_PASSWORD: {{"'{{ .MINECRAFT_RCON_PASSWORD }}'"}}
        SEED: {{"'{{ .MINECRAFT_SEED }}'"}}
  dataFrom:
    - extract:
        key: mc-mc
