controllers:
  minio:
    labels:
      nfsMount: "true"
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: quay.io/minio/minio
          tag: RELEASE.2024-04-18T19-09-19Z
        env:
          MINIO_API_CORS_ALLOW_ORIGIN: https://minio.dex136.xyz,https://s3.dex136.xyz
          MINIO_BROWSER_REDIRECT_URL: https://minio.dex136.xyz
          MINIO_PROMETHEUS_JOB_ID: minio
          MINIO_PROMETHEUS_URL: https://prometheus.dex136.xyz
          MINIO_PROMETHEUS_AUTH_TYPE: public
          MINIO_SERVER_URL: https://s3.dex136.xyz
          MINIO_UPDATE: "off"
        envFrom:
          - secretRef:
              name: &app minio
        args:
          - server
          - /data
          - --console-address
          - :9001
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /minio/health/live
                port: 9000
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 6
          readiness: *probes
        securityContext:
          privileged: true
          runAsUser: 99
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 3Gi
service:
  app:
    controller: *app
    ports:
      http:
        port: 9001
      s3:
        port: 9000
serviceMonitor:
  app:
    serviceName: *app
    endpoints:
      - port: s3
        scheme: http
        path: /minio/v2/metrics/cluster
        interval: 1m
        scrapeTimeout: 10s
ingress:
  app:
    className: internal
    hosts:
      - host: &host "{{ .Release.Name }}.dex136.xyz"
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts: [*host]
  api:
    enabled: true
    className: internal
    annotations:
      external-dns.alpha.kubernetes.io/target: external.dex136.xyz
    hosts:
      - host: &s3Host s3.dex136.xyz
        paths:
          - path: /
            service:
              identifier: app
              port: s3
    tls:
      - hosts: [*s3Host]
persistence:
  data:
    existingClaim: minio-data
    globalMounts:
      - path: /data
