app-template:
  controllers:
    minio:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        app:
          image:
            repository: quay.io/minio/minio
            tag: RELEASE.2024-04-06T05-26-02Z
          env:
            TZ: America/New_York
            MINIO_UPDATE: "off"
            MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring:9090
            MINIO_PROMETHEUS_JOB_ID: minio
            MINIO_PROMETHEUS_AUTH_TYPE: public
            MINIO_BROWSER_REDIRECT_URL: https://minio.dex136.xyz
            MINIO_SERVER_URL: https://s3.dex136.xyz
            MINIO_API_CORS_ALLOW_ORIGIN: https://minio.dex136.xyz,https://s3.dex136.xyz
          envFrom:
            - secretRef:
                name: minio
          args: ["server", "/data", "--console-address", ":9001"]
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /minio/health/live
                  port: &api-port 9000
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 750Mi
      pod:
        securityContext:
          runAsUser: 103
          runAsGroup: 103
          fsGroup: 103
          fsGroupChangePolicy: OnRootMismatch
  service:
    app:
      controller: minio
      ports:
        http:
          primary: true
          port: 9001
        api:
          port: *api-port
  serviceMonitor:
    app:
      serviceName: minio
      endpoints:
        - port: api
          scheme: http
          path: /minio/v2/metrics/cluster
          interval: 1m
          scrapeTimeout: 10s
  ingress:
    app:
      className: internal
      annotations:
        hajimari.io/icon: "pail"
        hajimari.io/enable: "true"
        hajimari.io/group: "system"
      hosts:
        - host: &console-host "minio.dex136.xyz"
          paths:
            - path: /
              service:
                identifier: app
                port: http
      tls:
        - hosts: [*console-host]
    s3:
      className: external
      annotations:
        hajimari.io/enable: "false"
        external-dns.alpha.kubernetes.io/target: external.dex136.xyz
      hosts:
        - host: &api-host s3.dex136.xyz
          paths:
            - path: /
              service:
                identifier: app
                port: api
      tls:
        - hosts: [*api-host]
  persistence:
    data:
      existingClaim: minio
      globalMounts:
       - path: /data
