---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: {{"'{{ .PAPERLESS_ADMIN_USER }}'"}}
        PAPERLESS_ADMIN_PASSWORD: {{"'{{ .PAPERLESS_ADMIN_PASSWORD }}'"}}
        PAPERLESS_SECRET_KEY: {{"'{{ .PAPERLESS_SECRET_KEY }}'"}}
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: paperless
        PAPERLESS_DBHOST: &dbHost postgres-rw.database.svc.cluster.local
        PAPERLESS_DBUSER: &dbUser "paperless"
        PAPERLESS_DBPASS: &dbPass {{"'{{ .PAPERLESS_POSTGRES_PASSWORD }}'"}}
        INIT_POSTGRES_DBNAME: paperless
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: {{"'{{ .POSTGRES_SUPER_PASS }}'"}}
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: postgres
