---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atuin-secret
    template:
      engineVersion: v2
      data:
        ATUIN_DB_URI: |-
          postgres://atuin:{{"{{ .ATUIN_POSTGRES_PASS }}"}}@pg-atuin-rw.database.svc.cluster.local/atuin
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: pg-atuin-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: atuin
        INIT_POSTGRES_PASS: {{"'{{ .ATUIN_POSTGRES_PASS }}'"}}
        INIT_POSTGRES_SUPER_PASS: {{"'{{ .ATUIN_POSTGRES_SUPER }}'"}}
  dataFrom:
    - extract:
        key: atuin
