---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .PG_PASSWORD }}` }}"
        username: "postgres"
  data:
    - secretKey: PG_PASSWORD
      remoteRef:
        key: pg.password
        property: password
