spegel:
  serviceMonitor:
    enabled: true
  spegel:
    containerdSock: /run/containerd/containerd.sock
    containerdRegistryConfigPath: /etc/cri/conf.d/hosts
  grafanaDashboard:
    enabled: true
  service:
    registry:
      hostPort: 29999
