controllers:
  alertmanager-discord:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        env:
          TZ: America/New_York
          DISCORD_USERNAME: alertmanager - aisling
          DISCORD_WEBHOOK:
            valueFrom:
              secretKeyRef:
                name: discord
                key: DISCORD_WEBHOOK
        image:
          repository: rogerrum/alertmanager-discord
          tag: 1.0.6@sha256:cfa615f24b7ec778ad0841c69527f798e713dfcadb7d7964dbe5b1821c767ebb
service:
  app:
    controller: alertmanager-discord
    ports:
      http:
        port: 9094
