apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pihole-monitor
  labels:
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - labels:
        job: pihole
      targets:
        - pihole-monitor.monitoring.svc.cluster.local:9517
