extraInitContainers:
  - name: 01-init-db
    image: ghcr.io/onedr0p/postgres-init:16
    envFrom:
      - secretRef:
          name: &secret grafana-secret
replicas: 1
envFromSecrets:
  - name: *secret
grafana.ini:
  analytics:
    check_for_updates: false
    check_for_plugin_updates: false
    reporting_enabled: false
  news:
    news_feed_enabled: false
  feature_toggles:
    publicDashboard: true
    angularDeprecationUI: false
  date_formats:
    use_browser_local: true
  security:
    angular_support_enabled: true
    cookie_samesite: grafana
  explore:
    enabled: true
  server:
    root_url: https://grafana.dex136.xyz
admin:
  existingSecret: grafana-admin
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default-folder
      - name: kubernetes
        orgId: 1
        folder: Kubernetes
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes-folder
      - name: nginx
        orgId: 1
        folder: Nginx
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/nginx-folder
      - name: victoriametrics
        disableDeletion: false
        editable: true
        folder: "VictoriaMetrics"
        options:
          path: /var/lib/grafana/dashboards/victoria-metrics
        orgId: 1
        type: file
datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - { name: Alertmanager, orgId: 1 }
      - { name: Loki, orgId: 1 }
      - { name: Prometheus, orgId: 1 }
    datasources:
      - name: Alertmanager
        type: alertmanager
        uid: alertmanager
        url: http://vmalertmanager-vm.monitoring:9093/
        access: proxy
        jsonData:
          handleGrafanaManagedAlerts: false
          implementation: prometheus
      - name: Loki
        type: loki
        url: http://loki.monitoring:3100
      - name: VictoriaMetrics
        type: prometheus
        uid: victoria
        access: proxy
        url: http://vmsingle-vm.monitoring.svc:8429/
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        isDefault: true
        url: http://vmsingle-vm.monitoring.svc:8429/
dashboards:
  default:
    argocd:
      gnetId: 14584
      revision: 1
      datasource: Prometheus
    longhorn:
      gnetId: 13032
      revision: 6
      datasource: Prometheus
    cloudflared:
      # renovate: depName="Cloudflare Tunnels (cloudflared)"
      gnetId: 17457
      revision: 6
      datasource:
        - { name: DS_PROMETHEUS, value: Prometheus }
    external-dns:
      # renovate: depName="External-dns"
      gnetId: 15038
      revision: 3
      datasource: Prometheus
    unpackerr:
      # renovate: depName="Unpackerr"
      gnetId: 18817
      revision: 1
      datasource:
        - { name: DS_PROMETHEUS, value: Prometheus }
    spegel:
      # renovate: depName="Spegel"
      gnetId: 18089
      revision: 1
      datasource:
        - { name: DS_PROMETHEUS, value: Prometheus }
    pihole:
      # renovate: depName="pi-hole-exporter"
      gnetId: 10176
      revision: 3
      datasource:
        - { name: DS_PROMETHEUS, value: Prometheus }
    cert-manager:
      url: https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json
      datasource: Prometheus
    external-secrets:
      url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
      datasource: Prometheus
  kubernetes:
    k8s-system-api-server:
      # renovate: depName="Kubernetes / System / API Server"
      gnetId: 15761
      revision: 17
      datasource: Prometheus
    k8s-views-global:
      # renovate: depName="Kubernetes / Views / Global"
      gnetId: 15757
      revision: 37
      datasource: Prometheus
    k8s-views-nodes:
      # renovate: depName="Kubernetes / Views / Nodes"
      gnetId: 15759
      revision: 29
      datasource: Prometheus
    k8s-views-namespaces:
      # renovate: depName="Kubernetes / Views / Namespaces"
      gnetId: 15758
      revision: 35
      datasource: Prometheus
    k8s-views-pods:
      # renovate: depName="Kubernetes / Views / Pods"
      gnetId: 15760
      revision: 28
      datasource: Prometheus
    k8s-volumes:
      # renovate: depName="K8s / Storage / Volumes / Cluster"
      gnetId: 11454
      revision: 14
      datasource: Prometheus
  victoriametrics:
    vm-cluster:
      # renovate: depName="VictoriaMetrics - cluster"
      gnetId: 11176
      revision: 37
      datasource:
        - name: "DS_PROMETHEUS"
          value: Prometheus
    vm-operator:
      # renovate: depName="VictoriaMetrics - operator"
      gnetId: 17869
      revision: 2
      datasource:
        - name: "DS_PROMETHEUS"
          value: Prometheus
    vm-vmalert:
      # renovate: depName="VictoriaMetrics - vmalert"
      gnetId: 14950
      revision: 11
      datasource:
        - name: "DS_PROMETHEUS"
          value: Prometheus
    vm-vmagent:
      # renovate: depName="VictoriaMetrics - vmagent"
      gnetId: 12683
      revision: 19
      datasource:
        - name: "DS_PROMETHEUS"
          value: Prometheus
  nginx:
    nginx:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
      datasource: Prometheus
    nginx-request-handling-performance:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
      datasource: Prometheus
plugins:
  - grafana-clock-panel
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - natel-discrete-panel
  - pr0ps-trackmap-panel
  - vonage-status-panel
serviceMonitor:
  enabled: true
ingress:
  enabled: true
  ingressClassName: internal
  annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/icon: grafana.svg
      gethomepage.dev/name: "Grafana"
      gethomepage.dev/group: Monitoring
  hosts:
    - grafana.dex136.xyz
persistence:
  enabled: false
testFramework:
  enabled: false
sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
    label: grafana_dashboard
    folderAnnotation: grafana_folder
    provider:
      disableDelete: true
      foldersFromFilesStructure: true
  datasources:
    enabled: false
