fullnameOverride: vm
experimentalDashboardsEnabled: false
victoria-metrics-operator:
  operator:
    disable_prometheus_converter: true
grafana:
  enabled: false
alertmanager:
  enabled: false
vmsingle:
  spec:
    retentionPeriod: "30d"
    storage:
      storageClassName: monitoring
      resources:
        requests:
          storage: 20Gi
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 1
        memory: 960Mi
  ingress:
    enabled: true
    hosts:
    - vms.dex136.xyz
vmalert:
  ingress:
    enabled: true
    hosts:
    - va.dex136.xyz
vmagent:
  enabled: false
kubelet:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeApiServer:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
