server:
  fullnameOverride: vl
  persistentVolume:
    enabled: true
    existingClaim: vl-data
  ingress:
    enabled: true
    ingressClassName: internal
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/icon: si-VictoriaMetrics-#621773
      gethomepage.dev/group: Monitoring
      gethomepage.dev/name: "Victoria Logs"
    hosts:
      - name: vl.dex136x.xyz
        path: /
        port: 9428
  serviceMonitor:
    enabled: true
fluent-bit:
  enabled: false
