apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pihole-password
    template:
      engineVersion: v2
      data:
        pihole-pass: '{{ .PIHOLE_PASSWORD }}'
  dataFrom:
    - extract:
        key: pihole
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-token
    template:
      engineVersion: v2
      data:
        api-token: '{{ .CLOUDFLARE_API_KEY }}'
  dataFrom:
    - extract:
        key: cloudflare
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-api-key
    template:
      engineVersion: v2
      data:
        api-token: '{{ .EXTERNAL_DNS_UNIFI_API_KEY }}'
  dataFrom:
    - extract:
        key: unifi
