provider: cloudflare
txtOwnerId: homelab
txtPrefix: k8s.
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token
extraArgs:
  - --ingress-class=external
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
interval: 5m
sources: ["crd", "ingress"]
triggerLoopOnEvent: true
serviceMonitor:
  enabled: true
policy: sync
