controllers:
  kromgo:
    replicas: 2
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/kashalls/kromgo
          tag: v0.4.3@sha256:c9148045a3e211ad46d416c3e3bb7ffd4c169a8b6f8e56df03ea68ed1ed5571b
        env:
          PROMETHEUS_URL: http://vmsingle-vm.monitoring:8429/
          SERVER_HOST: 0.0.0.0
          HEALTH_HOST: 0.0.0.0
          SERVER_PORT: 80
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /-/health
                port: 8888
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /-/ready
                port: 8888
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile: { type: RuntimeDefault }
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: &app kromgo
service:
  app:
    controller: kromgo
    ports:
      http:
        port: 80
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.dex136.xyz
    hosts:
      - host: "kromgo.dex136.xyz"
        paths:
          - path: /
            service:
              identifier: app
              port: http
persistence:
  config-file:
    type: configMap
    name: kromgo-configmap
    globalMounts:
      - path: /kromgo/config.yaml
        subPath: config.yaml
        readOnly: true
