controllers:
  qbittorrent:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/onedr0p/qbittorrent
          tag: 5.0.3@sha256:19597e4a5c5e52702ff6b4ea5c4b5f9f42433d6c2f1ef1d2db5964938bf44557
        env:
          TZ: America/New_York
          QBT_WEBUI_PORT: &port 80
          QBT_TORRENTING_PORT: &bittorrentPort 50413
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v2/app/version
                port: *port
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 10
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 4Gi
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
service:
  app:
    controller: qbittorrent
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 192.168.3.242
    ports:
      http:
        port: *port
      bittorrent:
        enabled: true
        port: *bittorrentPort
        protocol: TCP
ingress:
  app:
    className: internal
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Qbittorrent"
      gethomepage.dev/icon: qbittorrent.svg
      gethomepage.dev/group: Media
      gethomepage.dev/widget.type: qbittorrent
      gethomepage.dev/widget.url: http://qbittorrent.media
    hosts:
      - host: qb.dex136.xyz
        paths:
          - path: /
            service:
              identifier: app
              port: http
persistence:
  config:
    existingClaim: qbittorrent
  media:
    type: nfs
    server: 192.168.3.40
    path: /volume1/Torrents/
    globalMounts:
      - path: /torrents
