apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  repo: https://bjw-s.github.io/helm-charts
  version: 3.6.1
  releaseName: qbittorrent
  valuesFile: helmvalues.yaml
  namespace: media
resources:
- pvc.yaml
