apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: coredns
  repo: https://coredns.github.io/helm
  version: 1.30.0
  releaseName: coredns
  valuesFile: helmvalues.yaml
  namespace: kube-system
