---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft-secret
    template:
      engineVersion: v2
      data:
        RCON_PASSWORD: {{"'{{ .MINECRAFT_RCON_PASSWORD }}'"}}
        SERVER_NAME: {{"'{{ .MINECRAFT_SERVER_NAME }}'"}}
        SEED: {{"'{{ .MINECRAFT_SEED }}'"}}
  dataFrom:
    - extract:
        key: minecraft
