controllers:
  tautulli:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/tautulli/tautulli
          tag: v2.14.5@sha256:6017b491d8e9100a97391b639fff5824ad36a315c69aae3c9ed78407994a626e
        env:
          TZ: America/New_York
        command: ["/usr/local/bin/python", "Tautulli.py"]
        args: [
          "--config", "/config/config.ini",
          "--datadir", "/config",
          "--port", "80"
        ]
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /status
                port: &port 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext: &securityContext
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 1Gi
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
service:
  app:
    controller: tautulli
    ports:
      http:
        port: *port
ingress:
  app:
    className: internal
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Tautulli"
      gethomepage.dev/icon: tautulli.svg
      gethomepage.dev/group: Media
    hosts:
      - host: tautulli.dex136.xyz
        paths:
          - path: /
            service:
              identifier: app
              port: http
persistence:
  config:
    existingClaim: tautulli
  tmp:
    type: emptyDir
