---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media
  resources:
    requests:
      storage: 20Gi
