---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autobrr-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__SESSION_SECRET: {{"'{{ .AUTOBRR_SESSION_SECRET }}'"}}
  dataFrom:
    - extract:
        key: autobrr
