---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: media
  name: podcastdownload
spec:
  schedule: "0 */2 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: poddown
            image: ghcr.io/aisling136/podcastdownloader:0.3
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: podcasts
              mountPath: /podcasts
            - name: config-volume
              mountPath: /config
          volumes:
          - name: podcasts
            nfs:
              server: crypt
              path: /mnt/pool0/media/Podcasts
          - name: config-volume
            secret:
              secretName: podcasts
              items:
                - key: config
                  path: config.yaml
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            supplementalGroups:
              - 10000
