apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: podcasts
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: podcasts
  data:
  - secretKey: config
    remoteRef:
      key: podcasts
      property: pods.yaml
