apiVersion: v1
kind: Secret
metadata:
    name: podcasts
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:z42cizLf+LaCpmLszgaTfpiAyN+eaJC2F3F9eKI3nmm0f5n9bvxyyD8cmH68Wl50XyQhgC+X8BWIYOOEPXqWnuOmg2lTIagCBV9rZswY2WUIb6jK8LRlh4QG5hI+j1b+66V2vUp2OcUsJDqKRe5QQDMyYQy5ZrmseJnLF/RUS5viwmo/l1MK8v3/X09RkoFmayNC2bCpEnsORELA7HqTVLYqWOAP/mCEAli97SAo2Fj6gBrijSmxhuHdRMZOZvT+AaBJRkmVgvYv46pSsmEL5T0eQSwnsYG/X43giguYuftspdx9mJliXrz/K8o9BO3dppbo4Ov98pIPB25/J6RMek4L/YC9dDaL3aX/QwXZkfLWOGCzxGwOG0NY30bW/ETpOn8B8kt9mBKSrlMFpl5jUMfTiAh5qnSn8ACW2G47Bs8LK9HuXyGN9i4f5V3zOGd4uuXcch15SEW4DpyH1PBxz5es3toUQRj0RgyzfMiW5pQ09A5O5ThyRQlTckOXzPH3b3m3FQ9Ka/MsgTWwh5yo60Tvk5EjSMEg9oj5BZrrIMj7ryCNJbnyRJn+T6e5jKrDCix3Xr1NXoK2jY+89bhulWApZnnqfJx5c9Wdtx7yV1iqbMZE25kCG18hxCECMbxjcKlSLw+/ZVObO1Q4e/c5yYw9VpJmVtPGRRkn8v1aDRlVt7+vOeakPg==,iv:8h9Y/VJotS1NqyhkOCqOskh+xTsdcDDQDe5fjGMmeM8=,tag:Eh90GN1NjYrZmP31z8u7RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15j6twvva426zpeacwhpmvnfp90v9pctluluxx4v6aldpczulgfqszafkq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNjZDaVdQaS85aGhUaGVk
            MTV5SFhSS3ZaOFJWZUZzayt1akJFYU0zSGkwCnh2YS9IaVVDeFYxOVUwL0R3RFpP
            NkNEWFNDdDcxVkk2dFUxUmptRWNVOGMKLS0tIG1FVDQxaDl1bnBOZmNqZEZUbkR4
            ZzJlSER4Zk84aERqcDE4Nlh4QklVNk0Kp+b9UyTgSMPq1OpOED2YjezZaUD3PPfx
            T6NVAFdd5LTOWVxJ/dHmKWI1TEMwtOeXgUUfxHMOaPsh/qkiKvxhIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T15:53:27Z"
    mac: ENC[AES256_GCM,data:NsZu2PMg34u2JMzYwdpTBhGxeF5baVkqAoCinKDwHjOI/RfCB7W0x5LGTwi+fwgOJl0EK6C1tj9vYxPJnIC0FXd2EUXuqnbOhQ8Dm2qNvDZgPIDRGnhVXvIg9+2eIVEwwJuRloYRRlxAE6CnKPO4j6bSuYaJWJnJbXw7Pk9EaCc=,iv:6AVF0fsxky8iJ/HXEGTIlhtAbIM5atOptHjp6UUx4o0=,tag:lFj+jfweqoTCKAsdxQ0Heg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
