---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    template:
      engineVersion: v2
      data:
        SONARR__AUTH__APIKEY: '{{ .SONARR_API_KEY }}'
        SONARR__POSTGRES__HOST: &dbHost postgres-rw.database.svc.cluster.local
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: &dbUser "sonarr"
        SONARR__POSTGRES__PASSWORD: &dbPass '{{ .SONARR_POSTGRES_PASSWORD }}'
        SONARR__POSTGRES__MAINDB: sonarr_main
        SONARR__POSTGRES__LOGDB: sonarr_log
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: postgres
