apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: dragonfly
  repo: oci://ghcr.io/dragonflydb/dragonfly/helm
  version: v1.26.2
  releaseName: dragonfly
  valuesFile: helmvalues.yaml
  namespace: database
resources:
# renovate: datasource=github-releases depName=dragonflydb/dragonfly-operator
- https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/v1.1.8/manifests/crd.yaml
- externalsecret.yaml
- cluster.yaml
