#crds
crds:
  enabled: true
#Grafana - Dashboards Only
grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      annotations:
        grafana_folder: Kubernetes
#Disable the rest of it
alertmanager:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
coreDns:
  enabled: false
kubelet:
  enabled: false
kubeApiServer:
  enabled: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  enabled: false
defaultRules:
  create: false
cleanPrometheusOperatorObjectNames: true
prometheusOperator:
  enabled: false
