---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: {{"'{{ .RADARR_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: radarr
