---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: {{"'{{ .RADARR_API_KEY }}'"}}
        RADARR__POSTGRES__HOST: &dbHost postgres-rw.database.svc.cluster.local
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__USER: &dbUser "radarr"
        RADARR__POSTGRES__PASSWORD: &dbPass {{"'{{ .RADARR_POSTGRES_PASSWORD }}'"}}
        RADARR__POSTGRES__MAINDB: radarr_main
        INIT_POSTGRES_DBNAME: radarr_main
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: {{"'{{ .POSTGRES_SUPER_PASS }}'"}}
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: postgres
