---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media
  resources:
    requests:
      storage: 5Gi
