---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pg-atuin-secret
    template:
      engineVersion: v2
      data:
        password: '{{ .ATUIN_POSTGRES_SUPER }}'
        username: "postgres"
  dataFrom:
    - extract:
        key: atuin
