app-template:
  controllers:
    paperless:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: &app paperless
      initContainers:
        init-db:
          image:
            repository: ghcr.io/home-operations/postgres-init
            tag: 17
          envFrom: &envFrom
            - secretRef:
                name: paperless-secret
      containers:
        paperless:
          image:
            repository: ghcr.io/paperless-ngx/paperless-ngx
            tag: 2.16.1
          env:
            # Configure application
            PAPERLESS_REDIS_PREFIX: pngx
            PAPERLESS_URL: https://paperless.dex136.xyz
            PAPERLESS_PORT: "8000"
            PAPERLESS_TIME_ZONE: America/New_York
            PAPERLESS_WEBSERVER_WORKERS: "2"
            PAPERLESS_TASK_WORKERS: "2"
            # Configure Remote User auth
            PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "true"
            # Configure folders
            PAPERLESS_CONSUMPTION_DIR: /data/nas/consume
            PAPERLESS_DATA_DIR: /data/local/data
            PAPERLESS_EXPORT_DIR: /data/nas/export
            PAPERLESS_MEDIA_ROOT: /data/local/media
            # Configure folder importer
            PAPERLESS_CONSUMER_POLLING: "60"
            PAPERLESS_CONSUMER_RECURSIVE: "true"
            PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
            # Configure OCR
            PAPERLESS_OCR_LANGUAGES: eng
            PAPERLESS_OCR_LANGUAGE: eng
            # Configure redis integration
            PAPERLESS_REDIS: redis://dragonfly.dragonfly.svc.cluster.local:6379
            # Configure user permissions
            USERMAP_GID: "65542"
          envFrom:
          - secretRef:
              name: paperless-secret
          resources:
            requests:
              cpu: 15m
            limits:
              memory: 4096Mi
  service:
    paperless:
      controller: paperless
      labels:
        app: *app
      ports:
        http:
          port: 8000
  ingress:
    paperless:
      className: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/name: Paperless
        gethomepage.dev/icon: paperless.png
        gethomepage.dev/description: Document OCR Software
        gethomepage.dev/widget.type: paperlessngx
        gethomepage.dev/widget.url: http://paperless.default:8000
        gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_PAPERLESS_TOKEN}}` }}"
      hosts:
      - host: paperless.dex136.xyz
        paths:
        - path: /
          service:
            identifier: *app
            port: http
  persistence:
    config:
      existingClaim: paperless
      globalMounts:
        - path: /data/local
    nas:
      type: nfs
      server: 192.168.3.40
      path: /volume1/MediaLibrary/paperless
      globalMounts:
        - path: /data/nas
