controllers:
  bazarr:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/onedr0p/bazarr
          tag: 1.5.1@sha256:6e469bc2db7d3a462158687684da2533fb87c40be6a00504e7dfbe9342bc7266
        env:
          TZ: America/New_York
        envFrom:
          - secretRef:
              name: bazarr-secret
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: &port 6767
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext: &securityContext
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 1Gi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile: { type: RuntimeDefault }
service:
  app:
    controller: bazarr
    ports:
      http:
        port: *port
ingress:
  app:
    className: internal
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Bazarr"
      gethomepage.dev/icon: bazarr.svg
      gethomepage.dev/group: Media
      gethomepage.dev/pod-selector: >-
        app.kubernetes.io/instance in (
            bazarr
        )
    hosts:
      - host: bazarr.dex136.xyz
        paths:
          - path: /
            service:
              identifier: app
              port: http
persistence:
  config:
    existingClaim: bazarr-config
  config-cache:
    type: emptyDir
    globalMounts:
      - path: /config/cache
  config-log:
    type: emptyDir
    globalMounts:
      - path: /config/log
  media:
    type: nfs
    server: 192.168.1.8
    path: /volume1/MediaLibrary/
    globalMounts:
      - path: /media
        readOnly: true
