---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-default
  namespace: {{ .Release.Namespace }}
spec:
  cron: "5 */6 * * *"
  task: "snapshot"
  groups:
  - default
  retain: 4
  concurrency: 1
  labels:
    jobname: snapshot-twice-daily
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-default
  namespace: {{ .Release.Namespace }}
spec:
  cron: "15 8 */2 * *"
  task: "backup"
  groups:
  - default
  retain: 2
  concurrency: 1
  labels:
    jobname: backup-weekly
---
