---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tandoor-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: pg-tandoor-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: tandoor
        POSTGRES_USER: "tandoor"
        INIT_POSTGRES_DBNAME: tandoor
        INIT_POSTGRES_HOST: pg-tandoor-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: tandoor
        INIT_POSTGRES_PASS: {{"'{{ .TANDOOR_POSTGRES_PASS }}'"}}
        INIT_POSTGRES_SUPER_PASS: {{"'{{ .TANDOOR_POSTGRES_SUPER }}'"}}
        SECRET_KEY: {{"'{{ .TANDOOR_SECRET_KEY}}'"}}
        POSTGRES_PASSWORD: {{"'{{ .TANDOOR_POSTGRES_PASS }}'"}}
  dataFrom:
    - extract:
        key: tandoor
