apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpoller-secret
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_API_KEY: {{"'{{ .UNIFI_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: unifi
