---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__API_KEY: '{{ .RADARR_API_KEY }}'
        RADARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "radarr"
        RADARR__POSTGRES_PASSWORD: &dbPass '{{ .RADARR_POSTGRES_PASSWORD }}'
        RADARR__POSTGRES_MAIN_DB: radarr_main
        RADARR__POSTGRES_LOG_DB: radarr_log
        INIT_POSTGRES_DBNAME: radarr_main radarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: radarr
        property: api
    - secretKey: RADARR_POSTGRES_PASSWORD
      remoteRef:
        key: radarr
        property: pg
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: pg
        property: password
