app-template:
  controllers:
    radarr:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: &app radarr
      containers:
        radarr:
          image:
            repository: ghcr.io/home-operations/radarr
            tag: 5.25
          env:
            RADARR__AUTH__METHOD: External
            RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
            RADARR__APP__INSTANCENAME: radarr
            RADARR__SERVER__PORT: &port 80
            RADARR__LOG__DBENABLED: "False"
            RADARR__LOG__LEVEL: info
            RADARR__APP__THEME: dark
            TZ: America/New_York
          envFrom:
            - secretRef:
                name: radarr-secret
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: *port
                initialDelaySeconds: 10
                periodSeconds: 60
                timeoutSeconds: 5
                failureThreshold: 3
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 2Gi
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          runAsNonRoot: true
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups: [10000]
  service:
    radarr:
      controller: radarr
      labels:
        app: *app
      ports:
        http:
          port: *port
  ingress:
    radarr:
      className: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Radarr"
        gethomepage.dev/icon: radarr.svg
        gethomepage.dev/group: Media
        gethomepage.dev/widget.type: radarr
        gethomepage.dev/widget.url: http://radarr.media
        gethomepage.dev/widget.key: '{{ "{{HOMEPAGE_VAR_RADARR_TOKEN}}" }}'
      hosts:
        - host: "radarr.dex136.xyz"
          paths:
            - path: /
              service:
                identifier: *app
                port: http
  persistence:
    config:
      existingClaim: radarr
    config-cache:
      existingClaim: radarr-cache
      globalMounts:
        - path: config/MediaCover
    tmp:
      type: emptyDir
    media:
      type: nfs
      server: crypt
      path: /mnt/pool0/media
      globalMounts:
        - path: /media
