---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        GF_DATABASE_HOST: postgres-rw.database.svc.cluster.local:5432
        GF_DATABASE_NAME: grafana
        GF_DATABASE_PASSWORD: &dbPass "{{ `{{ .GRAFANA_PG_PASSWORD }}` }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_USER: &dbUser grafana
        INIT_POSTGRES_DBNAME: grafana
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ `{{ .POSTGRES_SUPER_PASS }}` }}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: pg
        property: password
    - secretKey: GRAFANA_PG_PASSWORD
      remoteRef:
        key: grafana
        property: pg
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: grafana-admin
    template:
      engineVersion: v2
      data:
        admin-user: admin
        admin-password: "{{ `{{ .GRAFANA_ADMIN_PASSWORD }}` }}"
  data:
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: grafana
        property: admin
