---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: minio
        property: user
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: minio
        property: password
