apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: promtail
  repo: https://grafana.github.io/helm-charts
  version: 6.16.6
  releaseName: promtail
  valuesFile: helmvalues.yaml
  namespace: monitoring
  apiVersions:
    - monitoring.coreos.com/v1
