controllers:
  autobrr:
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      init-db:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 16
        envFrom: &envFrom
          - secretRef:
              name: autobrr-secret
    containers:
      app:
        image:
          repository: ghcr.io/autobrr/autobrr
          tag: v1.51.1@sha256:747c682d8d59e72a202ee4239bafbd7cfa10b0fc3a6220b61446de73dbd0c956
        env:
          AUTOBRR__CHECK_FOR_UPDATES: "false"
          AUTOBRR__HOST: 0.0.0.0
          AUTOBRR__PORT: &port 80
          AUTOBRR__LOG_LEVEL: INFO
        envFrom: *envFrom
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/healthz/liveness
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 256Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile: { type: RuntimeDefault }
service:
  app:
    controller: autobrr
    ports:
      http:
        port: *port
ingress:
  app:
    className: internal
    hosts:
      - host: autobrr.dex136.xyz
        paths:
          - path: /
            service:
              identifier: app
              port: http
