---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pg-tandoor-secret
    template:
      engineVersion: v2
      data:
        password: '{{ .TANDOOR_POSTGRES_SUPER }}'
        username: "postgres"
  dataFrom:
    - extract:
        key: tandoor
