---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: atuin-secret
    template:
      engineVersion: v2
      data:
        ATUIN_DB_URI: |-
          postgres://atuin:{{ .ATUIN_POSTGRES_PASS }}@postgres-rw.database.svc.cluster.local/atuin
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: atuin
        INIT_POSTGRES_PASS: '{{ .ATUIN_POSTGRES_PASS }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
    - secretKey: ATUIN_POSTGRES_PASS
      remoteRef:
        key: atuin
        property: pg
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: pg
        property: password
