apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: intel-device-plugins-operator
  repo: https://intel.github.io/helm-charts
  version: 0.29.0
  releaseName: intel-device-plugins-operator
  namespace: kube-system
  includeCRDs: true
- name: intel-device-plugins-gpu
  repo: https://intel.github.io/helm-charts
  version: 0.29.0
  releaseName: intel-device-plugins-gpu
  namespace: kube-system
  valuesInline:
    name: intel-gpu-plugin
    sharedDevNum: 3
    nodeFeatureRule: false
