apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pihole-password
    template:
      engineVersion: v2
      data:
        pihole-pass: {{"'{{ .PIHOLE_PASSWORD }}'"}}
  dataFrom:
    - extract:
        key: pihole
