apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.9.14
  releaseName: external-secrets
  valuesFile: values.yaml
  namespace: external-secrets
resources:
  - clustersecretstore.yaml
