apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.10.4
  releaseName: external-secrets
  valuesFile: helmvalues.yaml
  namespace: external-secrets
  apiVersions:
    - monitoring.coreos.com/v1
- name: app-template
  repo: https://bjw-s.github.io/helm-charts
  version: 3.5.1
  releaseName: onepassword-connect
  valuesFile: onepasshelmvalues.yaml
  namespace: external-secrets
resources:
  - clustersecretstore.yaml
generators:
- ./secretgenerator.yaml
