apiVersion: v1
kind: Secret
metadata:
    name: minio
data:
    user: ENC[AES256_GCM,data:8VdXhRO37GPQMLQSWghrUGhdr7psaTovQeSsFpzzh7UvjmjrwYE78K6YQo0=,iv:ywJuydh9zH1AZ9fb1F1fMumiGDLxTPlUwLx7vVJHoR4=,tag:KsOjJ3eqmwSjtwbP9V0P9Q==,type:str]
    password: ENC[AES256_GCM,data:ZvPPtcGBVr2fFhYg5UhMYLRKXQeBWhdL7vEftNMhJGY8P35uETV5jTX5GFs=,iv:pdvPmA4UN8T1LYbVbPjw3ZcvOlNojyhzjknklb3E5EI=,tag:UWwBMZCgE2oJjIQRm9t5Qw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15j6twvva426zpeacwhpmvnfp90v9pctluluxx4v6aldpczulgfqszafkq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVGZUZE5zZ3dLVmVYQmhT
            Ny9NVnVTQi8vWmhib1lPRUJCTTNVMDRVdUhvCmQyZm1kV3VZLzE1Y1JPS0t2QVRO
            MGdBUWhTVzZtaGsvajRSUHRyMWFuMjQKLS0tIHBSUTkrZ3NLaUxHc0F2alVXa0pK
            RmJyNHBVSUhIV0tHZGJwZms4RFNmeTAK/hksE1dsxf08z5L+ZeAbDYxR3pBlSu0t
            eJCfL+SOsiaXTs+pUBJyqHRryZKo8KbgsUKG5jA9VGu7JQdYTCnEnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T16:29:00Z"
    mac: ENC[AES256_GCM,data:8gD+yCWkqQ2M0ZMzVZCZ+rhlO+5b5l1hb7+rOzrmsJm86F4Tx5Mj10mv5h7+zVZfs8ajxDcPF+lTVXZrAJY86MVp4n0G5CDujNUsiEZkmxrOhwzGCAwquMC6FcpDYVx+TSisDFJJgcf27YQ3bDYXELWFpqB5BGOtxVCE8ajMiYg=,iv:VkeFQGgAW1Nh3bqJj0c/M8ZfaKeAiG7jAEIgZQ/J8i0=,tag:HVBXOCvRA35/KffIU77POQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
