controllers:
  uptime-kuma:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        env:
          TZ: America/New_York
        image:
          repository: louislam/uptime-kuma
          tag: 1.23.13@sha256:96510915e6be539b76bcba2e6873591c67aca8a6075ff09f5b4723ae47f333fc
        ports:
          - name: http
            containerPort: 3001
            protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            memory: 150Mi
service:
  app:
    controller: uptime-kuma
    ports:
      http:
        port: 3001
        protocol: TCP
ingress:
  app:
    className: external
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/icon: uptime-kuma.svg
      gethomepage.dev/name: "Uptime Kuma"
      gethomepage.dev/group: Monitoring
      gethomepage.dev/pod-selector: ""
      external-dns.alpha.kubernetes.io/target: "external.dex136.xyz"
      nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header Accept-Encoding "";
          sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/uptime-kuma/dark.css"></head>';
          sub_filter_once on;
    hosts:
      - host: &host kuma.dex136.xyz
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts: [*host]
persistence:
  config:
    existingClaim: pvc-uptime-kuma
    advancedMounts:
      uptime-kuma:
        app:
          - path: /app/data
