apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  repo: https://bjw-s.github.io/helm-charts
  version: 3.1.0
  releaseName: uptime-kuma
  valuesFile: helmvalues.yaml
  namespace: monitoring
- name: raw
  repo: https://bedag.github.io/helm-charts/
  version: 2.0.0
  releaseName: pvc
  valuesFile: ../../templates/pvc.yaml
  namespace: default
  valuesInline:
    pvcs:
      - name: pvc-uptime-kuma
        storage: "2Gi"
