apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.10.0
  releaseName: ingress-nginx
  valuesFile: helmvalues-internal.yaml
  namespace: network
- name: ingress-nginx
  includeCRDs: false
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.10.0
  releaseName: ingress-nginx-external
  valuesFile: helmvalues-external.yaml
  namespace: network
