ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    config:
      enable-brotli: "true"
      enable-ocsp: "true"
      enable-real-ip: "true"
      hide-headers: Server,X-Powered-By
      hsts-max-age: 31449600
      keep-alive-requests: 10000
      keep-alive: 120
      proxy-body-size: 0
      proxy-buffer-size: 16k
      ssl-protocols: TLSv1.3 TLSv1.2
      use-forwarded-headers: "true"
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
