fullnameOverride: nginx-external
controller:
  replicaCount: 1
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.dex136.xyz
      io.cilium/lb-ipam-ips: 192.168.1.243
  ingressClassResource:
    name: external
    default: false
    controllerValue: k8s.io/external
  admissionWebhooks:
    objectSelector:
      matchExpressions:
        - key: ingress-class
          operator: In
          values: ["external"]
  allowSnippetAnnotations: true
  config:
    block-user-agents: "GPTBot,~*GPTBot*,ChatGPT-User,~*ChatGPT-User*,Google-Extended,~*Google-Extended*,CCBot,~*CCBot*,Omgilibot,~*Omgilibot*,FacebookBot,~*FacebookBot*"
    enable-brotli: "true"
    enable-ocsp: "true"
    enable-real-ip: "true"
    hide-headers: Server,X-Powered-By
    hsts-max-age: 31449600
    keep-alive-requests: 10000
    keep-alive: 120
    proxy-body-size: 0
    proxy-buffer-size: 16k
    ssl-protocols: TLSv1.3 TLSv1.2
    use-forwarded-headers: "true"
  extraArgs:
    default-ssl-certificate: network/dex136-xyz-tls
  terminationGracePeriodSeconds: 120
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespaceSelector:
        any: true
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/instance: nginx-external
          app.kubernetes.io/component: controller
