apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-api-key
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-api-key
    template:
      engineVersion: v2
      data:
        api-token: {{"'{{ .UNIFI_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: unifi
