apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-configmap
data:
  config.yaml: |
    metrics:
    - name: talos_version
      query: node_os_info{name="Talos"}
      label: version_id

    - name: kubernetes_version
      query: kubernetes_build_info{service="kubernetes"}
      label: git_version

    - name: cluster_node_count
      query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
      colors:
        - { color: "green", min: 0, max: 9999 }

    - name: cluster_pod_count
      query: sum(kube_pod_status_phase{phase="Running"})
      colors:
        - { color: "green", min: 0, max: 9999 }

    - name: cluster_cpu_usage
      query: round(avg(instance:node_cpu:ratio) * 100, 0.1)
      suffix: "%"
      colors:
        - { color: "green", min: 0, max: 35 }
        - { color: "orange", min: 36, max: 75 }
        - { color: "red", min: 76, max: 9999 }

    - name: cluster_memory_usage
      query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
      suffix: "%"
      colors:
        - { color: green, min: 0, max: 35 }
        - { color: orange, min: 36, max: 75 }
        - { color: red, min: 76, max: 9999 }

    - name: cluster_age_days
      query: round((time() - min(kube_node_created) ) / 86400)
      suffix: "d"
      colors:
        - { color: "green", min: 0, max: 9999 }

    - name: cluster_uptime_days
      query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
      suffix: "d"
      colors:
        - { color: "green", min: 2, max: 9999 }
        - { color: "orange", min: 1, max: 2 }
        - { color: "red", min: 0, max: 1 }

    - name: argocd_app_count
      query: count(argocd_app_info)
      colors:
        - { color: "green", min: 0, max: 9999 }

    - name: argocd_app_health
      query: round((count(argocd_app_info{health_status="Healthy"}) / count(argocd_app_info)) * 100, 0.1)
      suffix: "%"
      colors:
      - { color: "green", min: 100, max: 9999 }
      - { color: "orange", min: 75, max: 99 }
      - { color: "red", min: 0, max: 72 }
