---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: media
  resources:
    requests:
      storage: 5Gi
