controllers:
  unpackerr:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/unpackerr/unpackerr
          tag: 0.14.0@sha256:92e76f59dffc11379c1cb900bc4a4dd10bcb1ad15a8a34797fdf07e4d28f22f8
        env:
          TZ: America/New_York
          UN_WEBSERVER_METRICS: true
          UN_WEBSERVER_LOG_FILE: /logs/webserver.log
          UN_ACTIVITY: true
          UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local
          UN_SONARR_0_PATHS_0: /complete
          UN_RADARR_0_URL: http://radarr.media.svc.cluster.local
          UN_RADARR_0_PATHS_0: /complete
        envFrom:
          - secretRef:
              name: unpackerr-secret
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 4Gi
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
service:
  app:
    controller: unpackerr
    ports:
      http:
        port: 5656
serviceMonitor:
  app:
    serviceName: unpackerr
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
persistence:
  logs:
    type: emptyDir
  complete:
    type: nfs
    path: /volume1/Torrents/Completed
    server: 192.168.1.8
    globalMounts:
      - path: /complete
