---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qui-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__SESSION_SECRET: {{"'{{ .QUI_SESSION_SECRET }}'"}}
  dataFrom:
    - extract:
        key: qui
